name: VaylerynEssentials
author: Lucariatias
version: 0.0.1
main: io.github.vayleryn.vaylerynessentials.VaylerynEssentials
depend: [VaylerynLib]
permissions:
    vayleryn.essentials.boatsigns.create:
        description: Allows you to create boat signs
        default: op