name: ${project.name}
author: Lucariatias
version: ${project.version}
description: ${project.description}
main: io.github.vayleryn.vaylerynessentials.VaylerynEssentials
depend: [VaylerynLib]
commands:
    enchant:
        description: Enchants the item in your hand
        usage: /<command> [enchantment] [level]
    feed:
        description: Feeds a player
        usage: /<command> (player)
    fly:
        description: Allows a player to fly
        usage: /<command> (player)
    heal:
        description: Heals a player
        usage: /<command> (player)
    inventory:
        description: Opens someone's inventory
        usage: /<command> [player]
    itemmeta:
        description: Edits the item meta of the item in your hand
        usage: /<command> [setname|addlore|removelore] [name|lore]
    kit:
        description: Claims a kit
        usage: /<command> (kit)
    msg:
        description: Messages a player
        usage: /<command> [player] [message]
    repair:
        description: Repairs the item in your hand
        usage: /<command>
    setspawn:
        description: Sets the worlds spawn location
        usage: /<command>
    setwarp:
        description: Sets a warp at your current location
        usage: /<command> [name]
    spawn:
        description: Teleports you to your worlds spawn
        usage: /<command>
    spawner:
        description: Sets the entity a spawner will spawn
        usage: /<command> [entity type]
    spawnmob:
        description: Spawns mobs at your location
        usage: /<command> [entity type] [amount]
    sudo:
        description: Runs a command with elevated priveledges
        usage: /<command> [command]
    unsign:
        description: Unsigns written books
        usage: /<command>
    warp:
        description: Warps to a location
        usage: /<command> [warp]
permissions:
    vayleryn.essentials.boatsigns.create:
        description: Allows you to create boat signs
        default: op
    vayleryn.essentials.command.enchant:
        description: Allows you to enchant items by command
        default: op
    vayleryn.essentials.command.enchant.unsafe:
        description: Allows you to add "unsafe" enchantments when enchanting by command
        default: op
    vayleryn.essentials.command.feed:
        description: Allows you to feed players
        default: op
    vayleryn.essentials.command.fly:
        description: Allows you to fly
        default: op
    vayleryn.essentials.command.heal:
        description: Allows you to heal players
        default: op
    vayleryn.essentials.command.inventory:
        description: Allows you to open other people's inventories
        default: op
    vayleryn.essentials.command.itemmeta:
        description: Allows you to modify item meta
        default: op
    vayleryn.essentials.command.kit:
        description: Allows you to claim kits
        default: op
    vayleryn.essentials.command.msg:
        description: Allows you to message users
        default: true
    vayleryn.essentials.command.repair:
        description: Allows you to repair items
        default: op
    vayleryn.essentials.command.setspawn:
        description: Allows you to set the spawn
        default: op
    vayleryn.essentials.command.setwarp:
        description: Allows you to set a warp
        default: op
    vayleryn.essentials.command.spawn:
        description: Allows you to teleport to the spawn
        default: op
    vayleryn.essentials.command.spawner:
        description: Allows you to change the entity spawned by a spawner
        default: op
    vayleryn.essentials.command.spawnmob:
        description: Allows you to spawn mobs
        default: op
    vayleryn.essentials.command.sudo:
        description: Allows you to run a command with elevated priveledges
        default: op
    vayleryn.essentials.command.unsign:
        description: Allows you to unsign books
        default: true
    vayleryn.essentials.command.warp:
        description: Allows you to use warps
        default: op