name: ${project.name}
author: Lucariatias
version: ${project.version}
description: ${project.description}
main: io.github.vayleryn.vaylerynessentials.VaylerynEssentials
depend: [VaylerynLib]
permissions:
    vayleryn.essentials.boatsigns.create:
        description: Allows you to create boat signs
        default: op