name: ${project.name}
author: Lucariatias
version: ${project.version}
description: ${project.description}
main: io.github.vayleryn.vaylerynessentials.VaylerynEssentials
depend: [VaylerynLib]
commands:
    enchant:
        description: Enchants the item in your hand
        usage: /<command> [enchantment] [level]
    feed:
        description: Feeds a player
        usage: /<command> (player)
    heal:
        description: Heals a player
        usage: /<command> (player)
    itemmeta:
        description: Edits the item meta of the item in your hand
        usage: /<command> [setname|addlore|removelore] [name|lore]
    kit:
        description: Claims a kit
        usage: /<command> (kit)
    setspawn:
        description: Sets the worlds spawn location
        usage: /<command>
    spawn:
        description: Teleports you to your worlds spawn
        usage: /<command>
permissions:
    vayleryn.essentials.boatsigns.create:
        description: Allows you to create boat signs
        default: op
    vayleryn.essentials.command.enchant:
        description: Allows you to enchant items by command
        default: op
    vayleryn.essentials.command.enchant.unsafe:
        description: Allows you to add "unsafe" enchantments when enchanting by command
        default: op
    vayleryn.essentials.command.feed:
        description: Allows you to feed players
        default: op
    vayleryn.essentials.command.heal:
        description: Allows you to heal players
        default: op
    vayleryn.essentials.command.itemmeta:
        description: Allows you to modify item meta
        default: op
    vayleryn.essentials.command.kit:
        description: Allows you to claim kits
        default: op
    vayleryn.essentials.command.setspawn:
        description: Allows you to set the spawn
        default: op
    vayleryn.essentials.command.spawn:
        description: Allows you to teleport to the spawn
        default: op