name: ${project.name}
author: Lucariatias
version: ${project.version}
description: ${project.description}
main: io.github.vayleryn.vaylerynessentials.VaylerynEssentials
depend: [VaylerynLib]
commands:
    enchant:
        description: Enchants the item in your hand
        usage: /<command> [enchantment] [level]
    itemmeta:
        description: Edits the item meta of the item in your hand
        usage: /<command> [setname|addlore|removelore] [name|lore]
permissions:
    vayleryn.essentials.boatsigns.create:
        description: Allows you to create boat signs
        default: op
    vayleryn.essentials.command.enchant:
        description: Allows you to enchant items by command
        default: op
    vayleryn.essentials.command.enchant.unsafe:
        description: Allows you to add "unsafe" enchantments when enchanting by command
        default: op
    vayleryn.essentials.command.itemmeta:
        description: Allows you to modify item meta
        default: op